### PR TITLE
reflect x if the length of x is not a power of 2 in the smash function

### PR DESCRIPTION
**Pull request by KaiqianZhang**
Hi all,

I just added a small chunk of code in the `smash` function to reflect x if the length of x is not a power of 2. And the corresponding to result would be truncated back to the original length of x. Thanks!

Kaiqian

### CODE REVIEW

**Comment by KaiqianZhang** [comment]
I just added this behavior in the function details, please check~

**Comment by stephens999** [comment]
Hi @KaiqianZhang 
two things:
i) can you change the underlying functions smash.gaus and smash.poiss to both do the reflection instead of in the wrapper function smash? 

this is because we want those functions to work for non powers of two if called directly, not only through the wrapper. If they both work then you don't need the reflection in the wrapper..

ii) note that the return from smash.gaus can be a list (eg if both mean and variance are estimated), in which case your current code smash.gaus(..)[1:n] will not work. Similarly smash.pois can return a list of two vectors if the posterior mean is requested and again i think your current code will not work then. Can you fix that?

**Comment by KaiqianZhang** [comment]
Thanks for checking that for me! I will work on fixing those.

**Comment by KaiqianZhang** [comment]
Hi @stephens999,

As suggested, I did the following:

+ removed reflection from the wrapper `smash`, and added reflection to `smash.gaus`.
+ `smash.poiss` has already had a function called `reflect` to deal with this problem, so I did not touch it.
+ truncate should be fine now for the returned list of two vectors.
+ function details were added for `smash.gaus` as well.

Please let me know if anything else you want to change. Thanks!!

**Comment by pcarbo** [comment]
Thanks @KaiqianZhang. Can you please add an example (see `@examples` in `ashsmooth.R`) illustrating the use of the Gaussian and Poisson versions of smash when the length of the signal is not a power of 2?

**Comment by KaiqianZhang** [comment]
Sure, will do!

**Comment by KaiqianZhang** [comment]
Hi @pcarbo,

I just added the example and also debugged a bit for my previous code. The code should work for all cases when you set `v.est=TRUE` or `post.var=TRUE` or `joint=TRUE` in the `smash.gaus` function. Please let me know if other things are needed!

**Comment by pcarbo** [comment]
This is now being developed in the "notpowerof2" branch.

**Pull request closed without merging**
